### PR TITLE
Fix-interactions

### LINKED ISSUE #41: Change Interaction attributes to private
Currently attributes of interactions are public

### LINKED ISSUE #42: bug: `interaction` command doesn't parse argument `NOTE` correctly
Entering an `interaction` command with a 1-word note like `interaction 1 o/INTERESTED abc` creates an `Interaction` with an empty note, while a command like `interaction 1 o/INTERESTED ab cd` creates an `Interaction` with the note `cd`.

Seems like the index used for parsing the `NOTE` argument is off by 1.

### PR DESCRIPTION
**Pull request by MagnificentCreature**
fixed #42 and #41

Changes:
Make the fields in Interactions Class private
Change InteractionCommandParser parse command to rectify #42

### CODE REVIEW

File: src/main/java/seedu/address/model/person/Interaction.java [hunk 1]
```diff
@@ -22,13 +22,12 @@ public static enum Outcome {
...
         */
         public static boolean isValidOutcome(String test) {
-            System.out.println(test);
             return test.matches("INTERESTED|NOT_INTERESTED|FOLLOWUP_REQUIRED|UNKNOWN");
         }
     }
 
-    public final String interactionNote;
-    public final Outcome outcome;
+    private final String interactionNote;
```
Comment (zhyuhan) [inline src/main/java/seedu/address/model/person/Interaction.java:29]: I think we need getters for these now right?

File: src/main/java/seedu/address/logic/parser/InteractionCommandParser.java [hunk 2]
```diff
@@ -46,19 +45,19 @@ public Command parse(String args) throws ParseException {
         if (argMultimap.getValue(PREFIX_OUTCOME).isPresent()) {
             String outcomeString = argMultimap.getValue(PREFIX_OUTCOME).get().split("\\s+")[0];
             outcome = ParserUtil.parseOutcome(outcomeString);
-            String[] trimmedArgsParts = trimmedArgs.split("\\s+", 4);
-            if (trimmedArgsParts.length < 4) {
+            String[] trimmedArgsParts = trimmedArgs.split("\\s+", 3);
+            if (trimmedArgsParts.length < 3) {
                 note = "";
```
Comment (zhyuhan) [inline src/main/java/seedu/address/logic/parser/InteractionCommandParser.java]: nit: we can invert this `if` statement right, since `note` is initialized to an empty string

**Review by zhyuhan — CHANGES_REQUESTED** [review]
We need to add getters for  `Interaction` fields now that they are private.

Other than that, looks good!

File: src/main/java/seedu/address/model/person/Interaction.java (hunk 1 above)
Comment (MagnificentCreature) [reply src/main/java/seedu/address/model/person/Interaction.java:29]: Nope, iinw its just the toString that's really being used

File: src/main/java/seedu/address/logic/parser/InteractionCommandParser.java (hunk 2 above)
Comment (MagnificentCreature) [reply src/main/java/seedu/address/logic/parser/InteractionCommandParser.java]: Done

File: src/main/java/seedu/address/model/person/Interaction.java (hunk 1 above)
Comment (MagnificentCreature) [reply src/main/java/seedu/address/model/person/Interaction.java:29]: Edit: Yeap, fixed in PR #52

**Review by zhyuhan — APPROVED** [review]
LGTM!

**Review by lilozz2 — APPROVED** [review]
Looks good
